// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rczdwnocfvpjeofgwska.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJjemR3bm9jZnZwamVvZmd3c2thIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAzMDAzNDEsImV4cCI6MjA3NTg3NjM0MX0.H8xkdWbfDiEEk1ClFjOTskrdGR_kwkfpiBhrtpyG1Uc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});